### ISSUE TITLE
Não vejo ainda o codigo fonte

### ISSUE THREAD

**Issue by ghost** [ribeiro-domingos19/Y-Downloader#1]
mekie mano @ribeiro-domingos19 , esse projeto ainda esta em andamento ou ja terminaste. não estou a encontrar o _codigo_ fonte😂😂

**Comment by ribeiro-domingos19** [comment]
Criei ontem, ainda está em desenvolvimento @BelchiorQS 😂

**Comment by ghost** [comment]
> Criei ontem, ainda está em desenvolvimento @BelchiorQS 😂

ahãm,agora peguei a visão mano😂, vou aguardar
